### PR TITLE
Updated rune images from RIOT

### PR DESCRIPTION
**Pull request by Pwn2OwnLive**
Updated rune images from https://developer.riotgames.com/docs/lol#data-dragon
- Removed obsolete rune images
- Added missing rune images (like Omnistone)
- Changed key for those moved under a different rune path

The images used were from patch version [10.10.3208608](https://ddragon.leagueoflegends.com/cdn/dragontail-10.10.3208608.zip)

### CODE REVIEW

**Comment by TinyRaindrop** [comment]
> Changed key for those moved under a different rune path

does it affect Runes.lol and Runeforge, since they use their own runepage mapping?

**Comment by Rerago** [comment]
It shouldn't. Since we're remap the ID's to the correct ID's. So if the two plugins would return "other" IDs, they would be displayed incorrectly.

**Comment by Rerago** [comment]
But im not sure if this is an "update". Als example "8017.png" we got from 108x108 to 64x64.

But i will check this an revisit this PR.

**Comment by Pwn2OwnLive** [comment]
For future reference, the image folders in the zip file are not 100% correct. 
The changes I made were as follows:

**Inspiration**
- CelestialBody (removed)
- Kleptomancy (removed)
- Approach Velocity (image was found under Resolve)

**Precision**
- Last Stand (image folder was found under Sorcery)

**Resolve**
- Chrysalis (removed)
- Iron Skin (removed)
- Aftershock (image folder was named VeteranAftershock)
- Shield Bash (image folder was named MirrorShell)
- Unflinching (image folder was found under Sorcery)

**Comment by Rerago** [comment]
Ahhh so you took the files out of the client.

We could also write a script based on:

http://ddragon.leagueoflegends.com/cdn/10.10.3216176/data/en_US/runesReforged.json

**Comment by Soundofdarkness** [comment]
Or as alternative data source which usually works better than ddragon we could use this too:  [cdragon](http://raw.communitydragon.org/latest/plugins/rcp-be-lol-game-data/global/default/v1/perk-images/styles/)

**Comment by TinyRaindrop** [comment]
cdragon has all the same issues as [described here](https://github.com/Soundofdarkness/RuneBook/pull/23#issuecomment-636187096), also missing omnistone.

**Comment by Soundofdarkness** [comment]
That yes, but its usually better for fetching data from since its updating faster than ddragon. But yeah, generally, tested the pr too, everything seems to work, but I will still wait 1-2 days with merging if we maybe have an idea about how to improve the image quality.

**Comment by Pwn2OwnLive** [comment]
> cdragon has all the same issues as [described here](https://github.com/Soundofdarkness/RuneBook/pull/23#issuecomment-636187096), also missing omnistone.

Both sources have Omnistone. They just call it [MasterKey](http://raw.communitydragon.org/latest/plugins/rcp-be-lol-game-data/global/default/v1/perk-images/styles/inspiration/masterkey/).

`{
"id": 8358,
"key": "MasterKey",
"icon": "perk-images/Styles/Inspiration/MasterKey/MasterKey.png",
"name": "Prototype: Omnistone", ....
}`

**Review by Turb0Hawk — APPROVED** [review]

**Comment by Rerago** [comment]
@Soundofdarkness
with the merge of #123 this PR can actually be closed I think.

**Comment by Soundofdarkness** [comment]
Yup looks like it.
Thanks for the Work and Discussion around this PR everyone !

**Pull request closed without merging**
