### PR TITLE
Added an option to minimize the application to the system's tray

### PR DESCRIPTION
**Pull request by RYSKZ**
Hello, first of all, thank you to all of you for the work that you have put on this project, I have been using this for months and I couldn't be more happy with it :P

However, after having used it for so long I found that something was missing, I use the auto upload function of the favourite rune page a lot and I thought it would be a good idea to have the possibility of keeping the application open without messing up the taskbar so you can tottaly forget about runes.

So I have added that option to do exactly that, now you can hide the app inside the tray and pop it out whenever you want, either using the contextual menu with the right click or double clicking in the app icon. I have also added a checkbox inside the settings panel so the user can toggle this functionality whenever he or she pleases, everything is fully integrated with the rest of the code, the persistency is working too.

I have tried it in every possible scenario and it works perfectly, but, please, let me know it something is not working as intended.

Thanks!

### CODE REVIEW

**Comment by Soundofdarkness** [comment]
Hey !
First of all thank you for the kind words, even though I have to admit that in the last time, most changes came from others and not from me, including the feature you want to use with your addition. 
So far adding a minimize option sounds good to me, and I would be fine with adding it (after testing it a bit too, just in case a second pair of eyes can find issues). However this will take a bit of time since I'm currently ill (yet again), so its probably going to take a while. But when im able to work again I will gladly attempt to merge and push the update. 
Thank you very much for your work already !

**Comment by RYSKZ** [comment]
Hello!
Thank you for your response and don't worry, take all the time you need, please.
I hope you get better soon :)

**Comment by Soundofdarkness** [comment]
Thank you ! I have tested the PR now, works nicely aside from one smaller bug: If the setting is switched off (after being on in the same run), the window will disappear from the task bar and then appear again since the `e.preventDefault()` handler is not removed. I will just fix that in a commit directly after merge since its nothing big at all.
Thank you for the contribution, will be released in a few hours since I think my upload will take forever due to my ISP having issues with the Github release server in the last month or two (sadly an issue since 2019, sometimes it works, sometimes it doesn't)

**Comment by RYSKZ** [comment]
Sorry for not taking that into account, thanks for taking the time to fix it.
And don't worry about the release, take your time, I hope that problem is solved soon.

Have a nice day!

**Pull request merged**
