### PR TITLE
Auto accept match

### PR DESCRIPTION
**Pull request by 11Tuvork28**
This adds the ability to RuneBook to instantly auto accept a match, this can be toggled with a slider.

### CODE REVIEW

**Comment by Soundofdarkness** [comment]
Looks good from a quick look,
but this will be something I need to ask riot if we can implement that first, since until now I only validated that Runes are fine.
I hope it wont take long but usually it takes around a week or two for a response.

**Comment by Soundofdarkness** [comment]
Well, I just got a response from Riot. Unfortunately using the LCU (Client) API to automate anything in regards to champion select is currently not allowed. Which means I sadly need to decline this PR and similar features :/ Sorry.

**Comment by Soundofdarkness** [comment]
I'm pretty sure the difference is that with mobalytics, etc. it's clear that the user is actively on the pc, while with auto match accept and auto champion it's not. But I've asked for some more clarification anyway. Just going to keep it closed unless the situation changes.

**Comment by 11Tuvork28** [comment]
Yeah all good, I just use it for convenience tbh and I thought it would be fine since the api allows it and other programs have it too.

**Pull request closed without merging**
