### PR TITLE
Opgg add item sets

### PR DESCRIPTION
**Pull request by 11Tuvork28**
Adds item sets from op.gg, merge after #116 or else it will have conflicts

### CODE REVIEW

**Comment by Soundofdarkness** [comment]
Looks good ! Going to merge this now and I will try to release the update today if possible. 
Thank you !

**Comment by 11Tuvork28** [comment]
Thanks for merging, I'm in the middle of a lol game but I saw that I messed up with this PR because forgot to correct an if statement grrr.
In the tag page-list the if statement needs to be ``` if={opts.tab.active == "blitzgg" || opts.tab.active "opgg"}``` and not ``` f={opts.tab.active == "blitzgg" || "opgg"}``` maybe you could change it before you release it. Because otherwise the item set button will be shown on every page which is miss leading.

**Comment by Soundofdarkness** [comment]
Yep, I've already fixed that in local, just need to push it with the version bump, dont worry ^^
Just currently trying to figure out why I seem to have some performance issues with that build, but that might be something non-fixable in the short term.
+ I need to temporarily disable MetaSRC due to not working and presumably leaking memory due to a redirect loop.

**Comment by Soundofdarkness** [comment]
Okay actually, we need to wait with the release since somewhere within the op.gg plugin we seem to use somewhere around 700MB to load pages (at least for Lux, havent checked other champions), so we currently spike to around 1GB ram usage. Im going to try to take a look whats happening there, but that might take a bit.

**Comment by Soundofdarkness** [comment]
Moved the problem to #118 so its easier to find.

**Pull request merged**
