### PR TITLE
Fixed and rewrote opgg plugin

### PR DESCRIPTION
**Pull request by 11Tuvork28**
Fixed op.gg plugin by rewriting it and I added support for other modes(ARAM, U.R.F)

### CODE REVIEW

**Comment by 11Tuvork28** [comment]
So I think now it should be optimized and good to go  :)

**Comment by Soundofdarkness** [comment]
Looks good so far, going to already merge it, but it might take me a day or two until I can release it, sorry (mentioned why in #105 ).
Thank you !

**Comment by HannoMartinus** [comment]
Couldn't wait for the next release, ended up compiling it myself and it works perfectly. 
There's one small visual issue though. The scrollbar looks ugly, and I suggest you make it part of the inner box (where the arrow points)image
Thanks in advance!

**Comment by 11Tuvork28** [comment]
Hi @HannoMartinus thanks for the feedback, I'm aware of this issue and I'm working on it but its in a bigger UI rework. I'm gonna push a fix to my fork, if you want a fix for that and even more unreleased feature check it out meaning build it from source. But as always you can just wait for it to be included in the next release(s)

**Pull request merged**
