### PR TITLE
Itemset for blitzgg and an exporter for issue #97

### PR DESCRIPTION
**Pull request by 11Tuvork28**
Currently everything should work but I'm not sure if the league client automatically sees the json file that is created when an item set is viewed. But according to this [ItemSetbuilder](https://www.lol-item-sets-builder.com/) it should automatically pick it up.
I marked this as draft as it is not quite ready yet in my opinion, let me know what you think!

### CODE REVIEW

**Comment by Soundofdarkness** [comment]
First of all, thanks for the PR.
So far its a quite good start, but as you said yourself, some things aren't quite done yet.
I think the general concept of adding it as another button for the runeset is pretty good.
A few smaller issues that I've noticed so far:
1) Currently the writing of the itemset fails due to missing the fs import. (I guess that's probably just a mess up of the ide not auto importing it
2) The button for opening and uploading the item set is smaller + has no icon (but I guess that's just work in progress)
3) I'm not sure if the button for viewing the itemset should already upload it. I think it should be possible to view the itemset and then decide to upload it, at least if that's a possibility.
4) I think the item set tags correspond to the names of the category in the game, so its probably better to name them normally and see if the client accepts that. 
Aside from that it looks pretty good so far !

**Comment by 11Tuvork28** [comment]
> First of all, thanks for the PR. So far its a quite good start, but as you said yourself, some things aren't quite done yet. I think the general concept of adding it as another button for the runeset is pretty good. A few smaller issues that I've noticed so far:
> 
>     1. Currently the writing of the itemset fails due to missing the fs import. (I guess that's probably just a mess up of the ide not auto importing it
> 
>     2. The button for opening and uploading the item set is smaller + has no icon (but I guess that's just work in progress)
> 
>     3. I'm not sure if the button for viewing the itemset should already upload it. I think it should be possible to view the itemset and then decide to upload it, at least if that's a possibility.
> 
>     4. I think the item set tags correspond to the names of the category in the game, so its probably better to name them normally and see if the client accepts that.
>        Aside from that it looks pretty good so far !

Yeah pretty much the points I wanted to tackle anyways, as you can see I already added a seperate button. And yes the button icon/size is work in progess, I'm not really sure right now what icon to choose though.
For the item section in the json file, I don't think that the sections need to have special names as various sites name them differently but I'm working on getting this to work properly :)

**Comment by Soundofdarkness** [comment]
Looks good to me, thanks !
If you dont mind I would test it a bit tomorrow and then release it.
Only small detail that I would change (if thats alright for you) is to capitalize the first letter of the item set name, but thats something I can just do when I'm bumping the version number. 
Aside from that it looks like a really nice addition :)

**Comment by 11Tuvork28** [comment]
All good, I'm happy I could help and  I guess thats what you meant with the name of the item set:)

**Pull request merged**
