### PR TITLE
remove static rune mapping

### PR DESCRIPTION
**Pull request by Rerago**
This PR removes the static mappings of the runes.

To do this, the current version of Riot is pulled at startup and processed by two new functions, which should make maintenance easier.

Notes:

- The stat values (5001, 5002,5003,5005,5007,5008) are not included in the official json ([ref](https://github.com/RiotGames/developer-relations/issues/26)).Therefore they remain Static
- for runforge, 2 IDs had to remain static as well

PS: We should think about saving the Champ information and rune information locally so that we don't have to pull it every time we need to. Since they won't change during the patch anyway.
(But that has nothing to do with this PR)

### CODE REVIEW

**Comment by TinyRaindrop** [comment]
Amazing, this has been bugging my perfectionist brain for too long.

Would [this](https://github.com/Soundofdarkness/RuneBook/pull/23#issuecomment-636208406) be a logical next step? Force recheck for new images whenever game version changes. So that users get new data even before a new Runebook update is released.

**Comment by Soundofdarkness** [comment]
Looks good so far, will test this when im able to play league a bit, and that force recheck generally sounds like something useful to add later on, we should just take care of handling problems with ddragon updating later than the patch happens.

**Comment by Rerago** [comment]
@TinyRaindrop
There are still some ideas. But let's discuss them in an issue :)

@Soundofdarkness
Well currently you have to update Runebook. And I guess DDragon will always be faster than us.

And why do you have to play LOL to check the PR? :D

**Comment by Soundofdarkness** [comment]
@Rerago Yeah, well, I thought I can just change the runes through and check that all mappings fit (probably because of my distrust to ddragon due to numerous issues), but I guess I can just check a few later with opening random runepages and that should be enough. Will do that in a few hours.

**Comment by Soundofdarkness** [comment]
Yup, just tested it, from all I can tell without trying every rune it works beautifully, thanks :)
(and sorry for my first brain fuckup)

**Comment by Soundofdarkness** [comment]
Pulled the first idea into an issue:
#46

**Pull request merged**
