### PR TITLE
Updated dark theme for settings panel

### PR DESCRIPTION
**Pull request by Pwn2OwnLive**
- I have added two missing translations for Greek.

- I have updated the CSS for the dark theme regarding the settings panel #17.
I preferred to use IDs not to break the other pages and didn't use the white 
color as suggested as it was too bright for me.

**Preview**

DarkThemeSettings

DarkTheme2

### CODE REVIEW

**Comment by Rerago** [comment]
I'm not a fan of this version.

- we shouldn't introduce new IDs for this kind of thing. For example, what would we do if we introduced a green style? edit "i1-8n-dark"? That's not how we planned it with css.

- the text should not be gold. It has a grey/white colour in the main window which we should use here as well

- the shadow is still white behind the window

**Comment by Pwn2OwnLive** [comment]
The settings panel had already IDs from the owner that I used as well and 
I just added some more.

If you want to add more themes in the future you just add another CSS file
not add IDs and we change the *-dark to a more general name like *-theme
if that is the problem.

The text color is the same as the one used in the main app window (RuneBook,
CHAPTERS, CURRENT PAGE, etc), why go with a different option.

I don't understand to what white shadow you are referring to. Maybe it is
from the software I used to crop the screenshots.

**Comment by TinyRaindrop** [comment]
I agree with Rerago, it's not necessary to add "i18n-dark" ids, settings window can be styled by selecting "**.ui.modal** .whatever". 

Regarding colors, headings should be gold, but the other text - white, as it is in the main window.

**Comment by Pwn2OwnLive** [comment]
Updated dark settings CSS with no additinal IDs.

**Comment by Rerago** [comment]
What I mean by shadow is this:

settings

It's just still very bright. Also missing:

- no hover in Dropdown
- no hover on Button

And I am still for the fact that the dark.css and the light.css remain on the same level. In other words, they are identical except for the values used.

What do you think about when we merge #29 and take the translation from this PR with us?

**Comment by TinyRaindrop** [comment]
> And I am still for the fact that the dark.css and the light.css remain on the same level. In other words, they are identical except for the values used.

Strongly agree.

Ideally, we should have one main css file and two theme files with color variables. This would ensure easy styling and remove the need to update both dark and light.css every time something changes.

**Comment by Rerago** [comment]
> Ideally, we should have one main css file and two theme files with color variables. This would ensure easy styling and remove the need to update both dark and light.css every time something changes.

Oh yes sound nice.

```
<!-- All design changes like margins etc. -->
 <link rel="stylesheet" type="text/css" href="./runebook.css">

<!-- only with colour changes -->
<link rel="stylesheet" type="text/css" href={configfile.darktheme ? "dark.css" : "light.css"}>
```

But this is a topic for a different issue :D

**Comment by TinyRaindrop** [comment]
I meant like this:

`
<link rel="stylesheet" type="text/css" href={configfile.darktheme ? "dark.css" : "light.css"}>

 <link rel="stylesheet" type="text/css" href="./runebook.css">`

>prefers-color-scheme

we shouldn't assume too much)

**Comment by Pwn2OwnLive** [comment]
I agree that the two CSS files should remain in the same level, but none is in a good state,
as both have zero documentation on what they change. If someone in the future wants to 
create a new theme, why spend so much time deciphering it to just change some colors,
when one might not even have any CSS knowledge but wants to contribute.

So no offence I still prefer my version and one should spend some time to document and
bring the two CSS files to the same level. You are more than welcome to contribute to the
two remarks you made (no hover in Dropdown, no hover on Button) or I can check them
later on.

**Comment by Soundofdarkness** [comment]
Created an issue about the current problem of choosing which one to take: #39.

**Pull request merged**
