### PR TITLE
Show changelog modal after update to new version

### PR DESCRIPTION
**Pull request by TinyRaindrop**
Shows modal with the link to download page, so that people can read changelogs there. Alternatively, update the text on every release.

Greenshot 2020-06-09_21-41-59

### CODE REVIEW

**Comment by Soundofdarkness** [comment]
Yup, generally speaking I really like the new modal, but yep, we still need to integrate that with the dark theme.

**Comment by TinyRaindrop** [comment]
Will do

**Comment by TinyRaindrop** [comment]
Merged from upstream. Added dark theme.

**Comment by Soundofdarkness** [comment]
Yup, works nicely, thanks ! :)

**Pull request merged**
