### PR TITLE
Fix overflow issue

### LINKED ISSUE #18: Fix Scrolling
As I said in #3 there is a problem with scrolling since the updates. You can only see it when many pages are returned.

Normally it should scroll within the rune list.

### PR DESCRIPTION
**Pull request by TinyRaindrop**
Fixes #18 

2020-06-02 15_31_38-RuneBook

### CODE REVIEW

**Comment by TinyRaindrop** [comment]
Updated 
16_28-RuneBook
16_29-RuneBook

**Comment by Rerago** [comment]
Looks fine to me. We should just see what dark theme merge for conflict.

**Comment by TinyRaindrop** [comment]
I'm okay with merging this after dark settings, will check for any conflicts.

**Comment by Soundofdarkness** [comment]
I didn't merge this yet, due to #39, sorry for the wait.

**Comment by TinyRaindrop** [comment]
Resolved conflicts. Ready to be merged.

**Comment by Soundofdarkness** [comment]
Works perfectly, thanks :)

**Pull request merged**
