### PR TITLE
[METASrc] Let us call them what they call themselves

### PR DESCRIPTION
**Pull request by Rerago**

### CODE REVIEW

**Comment by TinyRaindrop** [comment]
Regarding Metasrc, perhaps keeping rune sets for inactive modes (Treeline, Blitz, Poro) doesn't make sense and only clutters the list.

**Comment by Rerago** [comment]
Yeah, I know. But do we always want to update the plugin when a mode is dropped?

The best I could come up with is to read out what is displayed on the page. If you don't remove them, unfortunately :(

**Comment by TinyRaindrop** [comment]
> But do we always want to update the plugin when a mode is dropped?

When it's dropped forever, like 3v3 and Blitz - yes. Those rune pages will never again be useful. In any case, modes don't get created and dropped very often.

Pages for recurring modes such as URF, on the other hand, will be useful, because the mode will be back eventually.

**Comment by Rerago** [comment]
So I built in testing. If a patch has delivered data in the last 3 patches it will be checked.

This has the advantage that if riot has the idea to reintroduce 3v3 the plugin would be ready :D

**Comment by Soundofdarkness** [comment]
Yup, works nicely too, thanks :) And well, I sadly don't think they will reintroduce these modes (aside from maybe sometimes NB, but we can still keep it that way, in case i'm wrong 👍

**Pull request merged**
